global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'telemetry-api'
    static_configs:
      - targets: ['telemetry-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'telemetry-ingestion'
    static_configs:
      - targets: ['telemetry-ingestion:8090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s 